source 'https://rubygems.org'

ruby '2.5.1'

gem 'jekyll', '3.9.0'
gem 'html-proofer', '3.10.0'
gem 'jekyll-sitemap'

gem 'jekyll-assets'
# jekyll-assets depends on sprockets, which depends on rack, which has two
# security vulnerabilities prior to 2.0.6.
# https://nvd.nist.gov/vuln/detail/CVE-2018-16471
# https://nvd.nist.gov/vuln/detail/CVE-2018-16470
gem "rack", ">= 2.1.4"

group :jekyll_plugins do
  gem 'jekyll-algolia', '~> 1.4', '>= 1.4.7'
end
